### ISSUE TITLE
Compiling agent/index.ts... agent/SwiftRuntime.ts:4:37 - error TS2314: Generic type 'NativeFunction<RetType, ArgTypes>' requires 2 type argument(s).

### ISSUE THREAD

**Issue by nmweizi** [neil-wu/FridaHookSwiftAlamofire#12]
Compiling agent/index.ts...
agent/SwiftRuntime.ts:4:37 - error TS2314: Generic type 'NativeFunction<RetType, ArgTypes>' requires 2 type argument(s).

**Comment by su-vikas** [comment]
I am facing same problem, were u able to fix this error?
